services:
  - type: web
    name: admoney
    env: node
    plan: free
    buildCommand: npm --prefix server install; npm --prefix frontend install; npm --prefix frontend run build
    startCommand: NODE_ENV=production npm --prefix server start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ADSENSE_ENABLED
        value: "false"
      - key: ADSENSE_CLIENT_ID
        sync: false
      - key: ADSENSE_SLOT_ID_VIEW_AD
        sync: false
